version: '3'
services:
  webapp:
    image: mintiens/webapp:latest  # Use the 'image' key to specify the existing image
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=mongodb://database:27017/mydb
    depends_on:
      - database

  database:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db

  test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_URL=http://webapp:3000
    depends_on:
      - webapp
    command: yarn test

volumes:
  mongodb-data:
