name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install

      - name: Run Lint
        run: yarn lint

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./webapp/Dockerfile  # Use the Dockerfile in the root directory
          push: false  # Do not push the image
          tags: |
            mintiens/webapp:latest  # Use the same tag as before
