name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # Add a step to install NodeJS
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 18

      # Add a step to install project dependencies
      - name: Install Dependencies
        run: yarn install

      # Add a step to run linting
      - name: Run Lint
        run: yarn lint
